from detected_person_identification.detectedPersonIdentifier import DetectedPersonIdentifier
from detected_person_identification.detectedPersonIdentificationStrategy import DetectedPersonIdentificationStrategy
from detected_person_identification.KNN_PersonIdentificationStrategy import KNN_DetectedPersonIdentificationStrategy
from detected_person_identification.knownPersonDb import KnownPersonDb
from detected_person_identification.knownPersonDb import KnownPersonFolderDb
from detected_person_identification.available_detected_person_identification_strategies import Available_DetectedPersonIdentificationStrategies